### ISSUE TITLE
work/requests.json not included

### ISSUE THREAD

**Issue by arlin** [jar398/tryphy#1]
all the tests invoke a main() function in webapp.py with a hard-coded reference to "work/requests.json".  This directory and file are not included in the distribution.  The lack of this file results in the same error when any test is run

> `IOError: [Errno 2] No such file or directory: 'work/requests.json'`

There is also a hard-coded references to work/exchanges.json.  

Add these files or explain in the README how to supply them.

**Comment by jar398** [comment]
Did you try: make work/requests.json  ?

I'll fix the README

**Comment by arlin** [comment]
Tried and did not work.  Here is the output (can't figure out how to format this in markdown): 

camel14:tryphy arlin$ make work/requests.json
wget -O in/PhyloServicesDescription.md "https://raw.githubusercontent.com/phylotastic/phylo_services_docs/master/ServiceDescription/PhyloServicesDescription.md"
--2018-08-27 15:50:55--  https://raw.githubusercontent.com/phylotastic/phylo_services_docs/master/ServiceDescription/PhyloServicesDescription.md
Resolving raw.githubusercontent.com... 151.101.200.133
Connecting to raw.githubusercontent.com|151.101.200.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52130 (51K) [text/plain]
Saving to: ‘in/PhyloServicesDescription.md’

100%[=============================================================>] 52,130      --.-K/s   in 0.06s   

2018-08-27 15:50:57 (884 KB/s) - ‘in/PhyloServicesDescription.md’ saved [52130/52130]

python doc_examples.py in/PhyloServicesDescription.md >work/requests.json.new
  File "doc_examples.py", line 55
    (group, specific_path) = webapp.parse_service_url(m.group(1)))
                                                                 ^
SyntaxError: invalid syntax
make: *** [work/requests.json] Error 1

**Comment by jar398** [comment]
Since the original documentation file has changed since I did this work, and I don't know how it has changed, I think the right thing to do is to put requests.json into the repository. Will commit in a minute.

This means that if there have been changes in the services, or if services have been added or removed, the tests won't know anything about these changes, and there will be no check detect inconsistencies.

**Comment by arlin** [comment]
Oh, I see.  You are getting this from our repo.  I will be working with Abu to update things.  Our goal (I think) is to get things updated so that the tests in this repo can be used as automatic regression tests for the web services repo.

**Comment by jar398** [comment]
It was fragile, to parse your documentation file like that, and I didn't adequately protect against what might happen if you changed it.

Added requests.json and exchanges.json.  See commit 8dc0c71.

**Comment by jar398** [comment]
I didn't test this fix in any way. You will surely let me know if the problem continues (or if the fix provokes a new one).

**Comment by arlin** [comment]
The tests run now, and some of them run completely.  Others spawn various errors.  Apparently other incompatibilities have emerged.  Expect a merge request from Abu and I.

**Comment by jar398** [comment]
I think it would be much better if you forked my repo so you can do as you wish with your version.  I don't see much reason to keep my version up to date - in the event I need to do more work I can re-fork your version.

**Comment by arlin** [comment]
@jar398, yes, there are better ways to do this.  In fact, Abu has taken all of your tests, and put them inside the tests directory in the web services repo, and he has expanded them to cover some new services.  All of that was done 4 months ago and I'm just realizing it now.
